name: "Seacrest WalletConnect Server"
description: "Boot a secure Seacrest WalletConnect Signing Proxy Server"
inputs:
  ethereum_url:
    description: "Ethereum node to proxy requests to"
    required: true
  port:
    description: "Port to host proxy on"
    required: true
    default: 8585
  requested_network:
    description: "Requested network to connect to"
runs:
  using: "composite"
  steps:
    - run: |
        cd ${{ github.action_path }}
        npm install
        LARGE=false RESHOW_DELAY=10000 REQUESTED_NETWORK="${{ inputs.network }}" node src/index.mjs "${{ inputs.ethereum_url }}" "${{ inputs.port }}" &
        while ! nc -z localhost "${{ inputs.port }}"; do
          sleep 0.1
        done
        curl -S -s -i "http://localhost:${{ inputs.port }}" -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}'
      shell: bash
branding:
  icon: 'server'
  color: 'yellow'
