name: 'Seacrest WalletConnect'
description: 'Boot a Seacrest WalletConnect Server'
inputs:
  ethereum:
    description: 'Ethereum node to proxy requests to'
    required: true
runs:
  using: "composite"
  steps:
    - run: npm install
      shell: bash
    - run: node src/index.mjs ${{ inputs.ethereum }}
      shell: bash
